# atlas.tf — MongoDB Atlas Flex cluster + project IP access list + db user.
#
# Live state (verified in job-0014, matches what's currently in Atlas):
#   - Cluster `grace-2-dev` (id 6a234a45e40bf4c4a1177833)
#   - Tier: Flex, backing GCP, region CENTRAL_US (== us-central1)
#   - MongoDB 8.0.24, disk 5 GB, backups enabled
#   - terminationProtectionEnabled: false
#   - tags: [] (cluster has no tags currently)
#
# The cluster is IMPORTED, not created. Provider settings (backing provider
# + region) are CREATE-only — change requires destroy/recreate. Do not flip
# them without coordinating a maintenance window.
#
# Notes on Flex (recorded for the audit):
#   - Use `mongodbatlas_flex_cluster`, NOT `mongodbatlas_cluster` or
#     `mongodbatlas_advanced_cluster`. Flex has its own dedicated resource
#     since provider v1.18 (we pin ~> 1.27 in versions.tf).
#   - The import ID format is `PROJECT_ID-CLUSTER_NAME` (hyphen-separated).
#     The org ID is NOT part of the import ID.
#   - Atlas region naming: `CENTRAL_US` (NOT `US_CENTRAL_1`).
#   - There is no `provider_name = "FLEX"` field on this resource; that
#     pattern belongs to `mongodbatlas_advanced_cluster`.

locals {
  # Workload-DB roles for the worker user: readWrite on the dev database
  # + read on `local` for replica-set metadata. No admin/clusterAdmin.
  worker_roles = [
    {
      role_name     = "readWrite"
      database_name = var.atlas_db_name
    },
  ]
}

# --- Flex cluster (imported) ---------------------------------------------

resource "mongodbatlas_flex_cluster" "dev" {
  project_id = var.atlas_project_id
  name       = var.atlas_flex_cluster_name

  provider_settings = {
    backing_provider_name = "GCP"
    region_name           = var.atlas_region_name
  }

  termination_protection_enabled = false

  tags = {
    project = "grace-2"
    env     = var.env
    sprint  = var.sprint
  }
}

# --- Project IP access list (imported) -----------------------------------
# The dev IPv4 /32 was added via `atlas accessLists create` in job-0014,
# then imported here. Cloud Run egress (Direct VPC egress + Cloud NAT
# with a reserved static IP) is a follow-up when actual Cloud Run services
# land — NOT in this job's scope.

resource "mongodbatlas_project_ip_access_list" "dev_ip" {
  project_id = var.atlas_project_id
  cidr_block = var.dev_ip_cidr
  comment    = "nate-debian-dev"
}

# --- Worker DB user (created by tofu; not imported) ----------------------
# SCRAM-SHA-256 user scoped to the dev database. Password is generated by
# the random provider and stored in Secret Manager (see secrets.tf) —
# never logged, never committed.

resource "random_password" "worker_pw" {
  length      = 32
  special     = true
  # Avoid characters that break SRV URIs without URL-encoding.
  override_special = "._-~"
}

resource "mongodbatlas_database_user" "worker" {
  project_id         = var.atlas_project_id
  username           = var.atlas_db_username
  password           = random_password.worker_pw.result
  auth_database_name = "admin"

  dynamic "roles" {
    for_each = local.worker_roles
    content {
      role_name     = roles.value.role_name
      database_name = roles.value.database_name
    }
  }

  scopes {
    name = var.atlas_flex_cluster_name
    type = "CLUSTER"
  }

  labels {
    key   = "project"
    value = "grace-2"
  }
  labels {
    key   = "env"
    value = var.env
  }
}
